#!/bin/bash

INSTANCE="${BLOCK_INSTANCE}"
IP_ADDRESS= ifconfig "${INSTANCE}" | awk '/inet addr/ {gsub("addr:", "", $2); print $2}'

if [[ "${IP_ADDRESS}" != "" ]]; then
  echo "${IP_ADDRESS}"
  echo "${IP_ADDRESS}"
  echo ""
fi
